[package]
name = "pacesetter-util"
version = "0.0.1"
edition = "2021"
authors = ["Marco Otte-Witte <marco.otte-witte@mainmatter.com>"]
description = "Meta-framework on top of axum"
license = "MIT"

[dependencies]
anyhow = "1"

[dev-dependencies]
insta = "1.34"
