[package]
name = "pacesetter-cli"
version = "0.0.1"
edition = "2021"
authors = ["Marco Otte-Witte <marco.otte-witte@mainmatter.com>"]
description = "CLI for Meta-framework on top of axum"
license = "MIT"

[[bin]]
name = "pace"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["cargo"] }
cargo-generate = "0.18"
