name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  cargo_check:
    name: "Cargo Check"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: cargo check
      uses: actions-rs/cargo@v1.0.1
      with:
        command: check

  rustfmt:
    name: "Rust Format"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: fmt
      uses: actions-rs/cargo@v1.0.1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy

    - name: clippy
      uses: actions-rs/cargo@v1.0.1
      with:
        command: clippy
        args: --all-targets -- -D warnings

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: test
      run: cargo test

  generate-full:
    name: Generate full example app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
            .
            my-app-full
      
      - name: generate
        run: cargo run -- --full my-app-full

  test-generated-full:
    name: "Test generated full example app"
    runs-on: ubuntu-latest
    needs: generate-full

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      postgres_test:
        image: postgres
        env:
          POSTGRES_DB: my_app_test
          POSTGRES_USER: my_app_test
          POSTGRES_PASSWORD: my_app_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-full

    - name: migrate
      run: |
        cd my-app-full
        cargo db reset
        cargo db reset -e test

    - name: test
      run: |
        cd my-app
        cargo test

  fmt-generated-full:
    name: "Validate format of generated full example app"
    runs-on: ubuntu-latest
    needs: generate-full
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-full
    
    - name: fmt-generated
      run: |
        cd my-app-full
        cargo fmt -- --check

  clippy-generated-full:
    name: "Run Clippy on generated full example app"
    runs-on: ubuntu-latest
    needs: generate-full

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-full
    
    - name: migrate
      run: |
        cd my-app-full
        cargo db reset

    - name: clippy-generated
      run: |
        cd my-app-full
        cargo clippy --all-targets -- -D warnings

  run-generated-full:
    name: "Run generated full example app"
    runs-on: ubuntu-latest
    needs: generate-full

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-full
    
    - name: migrate
      run: |
        cd my-app-full
        cargo db reset
        cargo db seed

    - name: run-generated
      run: |
        cd my-app-full
        cargo run & (timeout 120 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 3000)
        curl -X POST localhost:3000/tasks -H 'Authorization: 9974812642a36dbee625fa06b2463dbff832e17dcce3836dbb' -H 'Content-Type: application/json' -d '{"description": "do something"}'
        curl -X PUT localhost:3000/tasks -H 'Authorization: 9974812642a36dbee625fa06b2463dbff832e17dcce3836dbb' -H 'Content-Type: application/json' -d '[{"description": "do something else"}, {"description": "…and do another thing"}]'
        curl localhost:3000/tasks

  generate-default:
    name: Generate default example app
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
            .
            my-app-default
      
      - name: generate
        run: cargo run my-app-default
  
  test-generated-default:
    name: "Test generated default example app"
    runs-on: ubuntu-latest
    needs: generate-default
  
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      postgres_test:
        image: postgres
        env:
          POSTGRES_DB: my_app_test
          POSTGRES_USER: my_app_test
          POSTGRES_PASSWORD: my_app_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-default
  
    - name: test
      run: |
        cd my-app-default
        cargo test
  
  fmt-generated-default:
    name: "Validate format of generated default example app"
    runs-on: ubuntu-latest
    needs: generate-default
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-default
    
    - name: fmt-generated
      run: |
        cd my-app-default
        cargo fmt -- --check
  
  run-generators-with-generated-default:
    name: "Run generators on generated default example app"
    runs-on: ubuntu-latest
    needs: generate-default
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-default
    
    - name: generate-migration
      run: |
        cd my-app-default
        cargo generate migration CreatePeopleTable

    - name: generate-entity
      run: |
        cd my-app-default
        cargo generate entity Person

    - name: generate-entity-test-helper
      run: |
        cd my-app-default
        cargo generate entity-test-helper Person

    - name: generate-middleware
      run: |
        cd my-app-default
        cargo generate middleware rate-limit

    - name: generate-controller
      run: |
        cd my-app-default
        cargo generate controller message

    - name: generate-crud-controller
      run: |
        cd my-app-default
        cargo generate crud-controller people

    # check the generators didn't produce mal-formatted code (ignoring order of module declarations
    # since we don't control that and it depends on the exact names we use for the generated items)
    - name: fmt-generated
      run: |
        cd my-app-default
        cargo fmt -- --config reorder_modules=false --check

  clippy-generated-default:
    name: "Run Clippy on generated default example app"
    runs-on: ubuntu-latest
    needs: generate-default
  
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-default
    
    - name: clippy-generated
      run: |
        cd my-app-default
        cargo clippy --all-targets -- -D warnings
  
  run-generated-default:
    name: "Run generated default example app"
    runs-on: ubuntu-latest
    needs: generate-default
  
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-default
    
    - name: run-generated
      run: |
        cd my-app-default
        cargo run & (timeout 120 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 3000)

  generate-minimal:
    name: Generate minimal example app
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
            .
            my-app-minimal
      
      - name: generate
        run: cargo run -- --minimal my-app-minimal
  
  test-generated-minimal:
    name: "Test generated minimal example app"
    runs-on: ubuntu-latest
    needs: generate-minimal
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-minimal
  
    - name: test
      run: |
        cd my-app-minimal
        cargo test
  
  fmt-generated-minimal:
    name: "Validate format of generated minimal example app"
    runs-on: ubuntu-latest
    needs: generate-minimal
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-minimal
    
    - name: fmt-generated
      run: |
        cd my-app-minimal
        cargo fmt -- --check
  
  clippy-generated-minimal:
    name: "Run Clippy on generated minimal example app"
    runs-on: ubuntu-latest
    needs: generate-minimal
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-minimal
    
    - name: clippy-generated
      run: |
        cd my-app-minimal
        cargo clippy --all-targets -- -D warnings
  
  run-generated-minimal:
    name: "Run generated minimal example app"
    runs-on: ubuntu-latest
    needs: generate-minimal
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache-workspaces: |
          .
          my-app-minimal
    
    - name: run-generated
      run: |
        cd my-app-minimal
        cargo run & (timeout 120 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 3000)
        curl localhost:3000/greet
