name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  cargo_check:
    name: "Cargo Check"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: cargo check
      uses: actions-rs/cargo@v1.0.1
      with:
        command: check

  rustfmt:
    name: "Rust Format"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: fmt
      uses: actions-rs/cargo@v1.0.1
      with:
        command: fmt
        args: --all -- --check

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy

    - name: clippy
      uses: actions-rs/cargo@v1.0.1
      with:
        command: clippy
        args: --all-targets -- -D warnings

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: test
      run: cargo test

  generate-full:
    name: Generate full example app
    runs-on: ubuntu-latest

    env:
      PS_CLI_LOCAL_DEV: 1

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: generate
        run: cargo run --package pacesetter-cli -- --full my-app

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: my-app-full
          path: my-app
          if-no-files-found: error
          retention-days: 1

  test-generated-full:
    name: "Test generated full example app"
    runs-on: ubuntu-latest
    needs: generate-full

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      postgres_test:
        image: postgres
        env:
          POSTGRES_DB: my_app_test
          POSTGRES_USER: my_app_test
          POSTGRES_PASSWORD: my_app_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
      with:
        name: my-app-full
        path: my-app

    - name: migrate
      run: |
        cd my-app
        cargo db reset
        cargo db reset -e test

    - name: test
      run: |
        cd my-app
        cargo test

  fmt-generated-full:
    name: "Validate format of generated full example app"
    runs-on: ubuntu-latest
    needs: generate-full
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
      with:
        name: my-app-full
        path: my-app
    
    - name: fmt-generated
      run: |
        cd my-app
        cargo fmt --all -- --check

  clippy-generated-full:
    name: "Run Clippy on generated full example app"
    runs-on: ubuntu-latest
    needs: generate-full

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
      with:
        name: my-app-full
        path: my-app

    - name: migrate
      run: |
        cd my-app
        cargo db reset

    - name: clippy-generated
      run: |
        cd my-app
        cargo clippy --all-targets -- -D warnings

  run-generated-full:
    name: "Run generated full example app"
    runs-on: ubuntu-latest
    needs: generate-full

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: my_app
          POSTGRES_USER: my_app
          POSTGRES_PASSWORD: my_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
      with:
        name: my-app-full
        path: my-app

    - name: migrate
      run: |
        cd my-app
        cargo db reset
        cargo db seed

    - name: run-generated
      run: |
        cd my-app
        cargo run & (timeout 120 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 3000)
        curl -X POST localhost:3000/tasks -H 'Authorization: 9974812642a36dbee625fa06b2463dbff832e17dcce3836dbb' -H 'Content-Type: application/json' -d '{"description": "do something"}'
        curl localhost:3000/tasks
